import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import styled from "@emotion/styled";
import Header from "../components/header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Front-end Developer" />
      <StyledWrapper>
        <Grid container>
          <Grid item xs={12} md={8} height={430} sx={{ position: "relative" }}>
            <Image
              src={
                "https://raw.githubusercontent.com/bannanaz/images/main/img/sayhi2.jpg"
              }
              alt="Say hi, vanilla JS commentbox"
              layout={"fill"}
              objectFit={"cover"}
            />
            <StyledOverlay>
              <StyledTextOverlay>Say hi!</StyledTextOverlay>
            </StyledOverlay>
          </Grid>
          <Grid item xs={12} md={4} height={430} sx={{ position: "relative" }}>
            <Image
              src={
                "https://raw.githubusercontent.com/bannanaz/images/main/img/calculator.png"
              }
              alt="Chart from covid-tracker"
              layout={"fill"}
              objectFit={"cover"}
            />
            <StyledOverlayBlack>
              <StyledTextOverlay>Calculator</StyledTextOverlay>
            </StyledOverlayBlack>
          </Grid>
          <Grid
            item
            xs={12}
            md={4}
            height={430}
            sx={{ position: "relative", object: "fit" }}
          >
            <Image
              src={
                "https://raw.githubusercontent.com/bannanaz/images/main/img/covid_chart.jpg"
              }
              alt="Calculator in white design"
              layout={"fill"}
              objectFit={"cover"}
            />
            <StyledOverlayBlack>
              <StyledTextOverlay>Covid tracker</StyledTextOverlay>
            </StyledOverlayBlack>
          </Grid>
          <Grid item xs={12} md={8} height={430} sx={{ position: "relative" }}>
            <Image
              src={
                "https://raw.githubusercontent.com/bannanaz/images/main/img/splendid4.jpg"
              }
              alt="Splendid online rental service"
              layout={"fill"}
              objectFit={"cover"}
            />
            <StyledOverlay>
              <StyledTextOverlay>Splendid</StyledTextOverlay>
            </StyledOverlay>
          </Grid>
        </Grid>
      </StyledWrapper>
    </div>
  );
}

const StyledWrapper = styled.div`
  width: 85%;
  margin-left: auto;
  margin-right: auto;
  padding: 25px 0px 0px 0px;
  @media screen and (max-width: 600px) {
    width: 90%;
    padding-top: 0px;
    padding-bottom: 25px;
  }
`;

const StyledOverlay = styled.div`
  opacity: 0;
  cursor: pointer;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  transition: 0.7s ease;
  background-color: #fc4046;
  z-index: 5;

  :hover {
    opacity: 0.96;
    cursor: pointer;
  }
`;

const StyledTextOverlay = styled.div`
  color: white;
  font-size: 40px;
  font-weight: 600;
  font-family: "Montserrat", sans-serif;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
`;

const StyledOverlayBlack = styled.div`
  opacity: 0;
  cursor: pointer;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  transition: 0.7s ease;
  background-color: black;
  z-index: 5;

  :hover {
    opacity: 0.85;
    cursor: pointer;
  }
`;
